# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99961c5ceef3f213428e53947dc9315b3e32117e19ec078392486608f1b476346282b3cc52de59b273863601ecc878c0a79f85be7b3c862e6e8c81065a84433b

test:
  secret_key_base: d5df371f68eb1666c5efc7b7dfa9a410a0370cae7212ba561e970ee79c8e1c86dbac4a2a8713565cbe209a96890a2dabedcebe0db8a1406dca756472f42073b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
